[[Birch_Standard]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10a43fa9562ee58781297b70fb74b020309df781"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "62369cee2f96d2e5dbe5097b7972f1f917c2c65ab0454f5821682e6e026bcc0a"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Birch_Standard]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e1465ac47d1076f6bc57269c5d228d7f9aaefaa"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "0152ad1a5ac7dade4c7a1a3b14bf87e34df6784b0fabff4bb65d2b5f1089e507"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Birch_Standard]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c10a2b9d087d6fa9578878da53ac808e91a1648d"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "e147d10e2ca7eca9a8678f0bec30396dda43230dcfdc31d9e992f266494e944d"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.aarch64-linux-musl-cxx03.tar.gz"
[[Birch_Standard]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc02d23b460b64d3f935f2d62569add0543b2119"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "a5eb1deb7e7d6db5fe71d360c9213dd33dfd8a7344779796995fe95f51324495"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.aarch64-linux-musl-cxx11.tar.gz"
[[Birch_Standard]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c7958312d5f4e204b07bb11f1fb41fb4171b544"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "8cb45e1fc79ebe3c708d909064ef0fdd7f00749ce0bc6f3e3361c5546f93ec69"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Birch_Standard]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63bfa45b9b2dc64f5598d13391ff7a0699938455"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "52de9bcea1765f7e0f918e048167b080f5652e8921945775388b4a374ec17c83"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Birch_Standard]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a04db7b98fbdf95815dfbe246138b0a8467630b7"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "e59ff288272b6de13261285b83cfdb2b87b7155c2737d7e0d92a129c2f31840d"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Birch_Standard]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e8a6d7b71659d5d16f4079d0ecf848e13572afb"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "08594a0a3e4c2a3d756914f725e9e9429c5a1a5e1f2d7f15a898e3aa7c596d0a"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Birch_Standard]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "605fb853b3748205090ea63c3fc50a5f5621bd92"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "bcaccf4a9c7391636797ae951850e3fe4aec5bdc44a8073ebc5cdb15487aa6d0"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.i686-linux-gnu-cxx03.tar.gz"
[[Birch_Standard]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3737dea214f8187c647ed9fde89b6a536c0bdce1"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "9de831ec02af7b96a13e5582b0a0698a7448ebd698ce52935bc38ee6d0405c99"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.i686-linux-gnu-cxx11.tar.gz"
[[Birch_Standard]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f77efd927aa7faf94ddbe95d98c5fd2b34a914a"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "4b16996cb2461916cbe137aa6b1acbfb8bc43498c5965cc44bed7487feb6461e"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.i686-linux-musl-cxx03.tar.gz"
[[Birch_Standard]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2532f45e0ed56af7f9214f54afff232ccf5b9bf"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "4f7a489e494823d5a333abafdb83839628d1d398cf5d32f0dec94b1219eecb49"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.i686-linux-musl-cxx11.tar.gz"
[[Birch_Standard]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f390e860cc72d6aae19edb45a2bedec2d5b8d3e3"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "18a9edeb26d5859b3e08e4bda0320f293d6613a44ead04136d8451f414fa0770"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Birch_Standard]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "712717769c761157e0473d1bd11b921cd3766e98"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "6cc230f2e1681af9a16ab38f2e5e229f022aa98c2d2a38a6bbebf953654cb6c3"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Birch_Standard]]
arch = "x86_64"
git-tree-sha1 = "6f5420c76a07580a49439497cfa9ba6e059247ac"
os = "macos"

    [[Birch_Standard.download]]
    sha256 = "43e07797ce38ccf1ff3ed40c28da7a46a8bfc9fadd016d3e5334e7bca9cb8049"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.x86_64-apple-darwin.tar.gz"
[[Birch_Standard]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f2f1c85121907bed46de1644d35dac42797448f"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "4a01bcc88a0b2d21b3fd2bf6b129be4bd4bcb3410b0094524e875ba999181635"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Birch_Standard]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4fd37bef85d356a3105ed54038f62264704bd05"
libc = "glibc"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "a31cc4bf9c3e4c50069ea37bcfe04105d836c4a534dbd7050dd306c2ac5434f4"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Birch_Standard]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c479fb66d48677acb0b2be8ce2d29d4b78408962"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "62f4c74c66a3d65bb5e0cd1aec067c4901955605bc2cde367c289b5ad4e8ffc1"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.x86_64-linux-musl-cxx03.tar.gz"
[[Birch_Standard]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21daf94c33acc3f462f24208f56a44008305638a"
libc = "musl"
os = "linux"

    [[Birch_Standard.download]]
    sha256 = "62f9023e25ab1b8ddb6fecc039afd09aaf2dc11a10ece655f11950bd74b61da9"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.x86_64-linux-musl-cxx11.tar.gz"
[[Birch_Standard]]
arch = "x86_64"
git-tree-sha1 = "830d362ece25dcd5fd491a1ed3e80dbcd45a3522"
os = "freebsd"

    [[Birch_Standard.download]]
    sha256 = "7cfc9de10d5e1bc000e4c33a4eb6d4e3af0551f705ca7b695c822f49d3759914"
    url = "https://github.com/JuliaBinaryWrappers/Birch_Standard_jll.jl/releases/download/Birch_Standard-v1.104.0+0/Birch_Standard.v1.104.0.x86_64-unknown-freebsd.tar.gz"
